#!/bin/bash

# MongoDB Atlas IP Whitelist Fix Guide
# Run this to get all necessary information

echo "════════════════════════════════════════════════════════════════"
echo "        MONGODB ATLAS CONNECTION FIX GUIDE"
echo "════════════════════════════════════════════════════════════════"
echo ""

# Get public IP
PUBLIC_IP=$(dig +short myip.opendns.com @resolver1.opendns.com 2>/dev/null)
if [ -z "$PUBLIC_IP" ]; then
    PUBLIC_IP=$(curl -s ifconfig.me 2>/dev/null)
fi

echo "📍 YOUR CURRENT PUBLIC IP ADDRESS:"
echo "   $PUBLIC_IP"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "🔧 STEP-BY-STEP FIX:"
echo ""
echo "1. Open MongoDB Atlas in your browser:"
echo "   https://cloud.mongodb.com/"
echo ""
echo "2. Login with your credentials"
echo ""
echo "3. Select your cluster: 'Semester-Cluster'"
echo ""
echo "4. Click 'Network Access' in the left sidebar"
echo "   (Or go to: Security → Network Access)"
echo ""
echo "5. Click the green 'ADD IP ADDRESS' button"
echo ""
echo "6. Choose ONE of these options:"
echo ""
echo "   Option A - Add Your Current IP (Recommended):"
echo "   ┌─────────────────────────────────────────────┐"
echo "   │  IP Address: $PUBLIC_IP           │"
echo "   │  Comment: Development Machine               │"
echo "   └─────────────────────────────────────────────┘"
echo ""
echo "   Option B - Allow From Anywhere (Testing Only):"
echo "   ┌─────────────────────────────────────────────┐"
echo "   │  IP Address: 0.0.0.0/0                      │"
echo "   │  Comment: Allow All (Remove Later!)         │"
echo "   └─────────────────────────────────────────────┘"
echo ""
echo "7. Click 'Confirm'"
echo ""
echo "8. Wait 1-2 minutes for changes to apply"
echo ""
echo "9. Restart your backend server:"
echo "   cd ~/Desktop/DBProject/E-Commerce-Project/Backend"
echo "   node server.js"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ WHAT TO EXPECT AFTER FIXING:"
echo ""
echo "   ✓ MongoDB connected successfully"
echo "   ✓ Server running at http://localhost:5000"
echo "   ✓ Socket.IO enabled"
echo "   ✓ Real-time features active"
echo "   ✓ Transactions ready"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "🆘 ALTERNATIVE: Use Local MongoDB"
echo ""
echo "If you can't access MongoDB Atlas, install local MongoDB:"
echo ""
echo "   # Install MongoDB"
echo "   sudo apt-get update"
echo "   sudo apt-get install -y mongodb-org"
echo ""
echo "   # Start as replica set (required for transactions)"
echo "   sudo mkdir -p /data/db"
echo "   sudo chown -R \$USER:\$USER /data/db"
echo "   mongod --replSet rs0 --dbpath /data/db --fork --logpath /data/db/mongod.log"
echo ""
echo "   # Initialize replica set"
echo "   mongosh --eval 'rs.initiate()'"
echo ""
echo "   # Update Backend/.env:"
echo "   MONGO_URI=mongodb://localhost:27017/ecommerce?replicaSet=rs0"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📞 Need Help? Check these docs:"
echo "   - Documentation/REALTIME_TRANSACTIONS_GUIDE.md"
echo "   - Documentation/REALTIME_QUICK_REFERENCE.md"
echo ""
echo "════════════════════════════════════════════════════════════════"
